"use server";

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function createRecruits() {
  const recruits = [
    ["1101", "LEE QI HAN"],
    ["1102", "AUBDHOOOLL HAKHEEM BIN MUHAMMAD SHAFEE"],
    ["1104", "TEYTEE CHONG"],
    ["1105", "MUHAMAD DANIAL AIMAN BIN ABDUL MAJID SALIM"],
    ["1106", "TAN JUN WEI"],
    ["1107", "TAN MING JIE ROYSTON"],
    ["1108", "QUEK LI XUAN JACOB"],
    ["1109", "JOTHAM SIM"],
    ["1110", "GUCON RAFFAELE VRYAN MANCENIDO"],
    ["1111", "HAIZAL CHEW"],
    ["1112", "MAH WAN XING, WILSON"],
    ["1113", "MUHAMMAD AQIL BIN HAMDAN"],
    ["1114", "CHING TSE HIAN"],
    ["1115", "JOEL TAN YIN SHEN"],
    ["1116", "JEFFREY ZHONG ZENG JIE"],
    ["1201", "ANDREW ALAN DEMERIN MORENO"],
    ["1202", "BRANDON POON XIN WEI"],
    ["1203", "PEH SAY EE"],
    ["1204", "MUHAMMAD DANISH DASUKI BIN MUHAMMAD FIRMAN"],
    ["1205", "TIEW CHUAN YONG"],
    ["1206", "NG DONG LIM, CALVIN"],
    ["1207", "AVANESH S/O BALACHANDRAN"],
    ["1208", "LIM QIAN QIU"],
    ["1209", "ESMON TAY JING HAN"],
    ["1210", "BOLLEPALLI TEJASWIN"],
    ["1211", "MUHAMMAD SHAHIRAN BIN SAZALI"],
    ["1212", "CHING JAXON"],
    ["1213", "LAI XIN RONG"],
    ["1214", "TREVAR CHOO"],
    ["1215", "NORAFIQ AMANI BIN NORRAIMI"],
    ["1216", "DYLAN TAN"],
    ["1301", "EDDIE KOH KAI YUAN"],
    ["1302", "NADIY NASRULHAQ BIN ZAKKY"],
    ["1303", "KEGAN NG REN JIE"],
    ["1304", "MUHAMMAD RAZIQ AMALI BIN ANUAR"],
    ["1305", "KARTHIKEYAN MOTHEESWARAN"],
    ["1306", "CHAN WEN RUI DASHIELL"],
    ["1307", "CHARLES NG ZONG YEW"],
    ["1308", "CHOI KIT"],
    ["1310", "AMIRUL AFFIQ BIN IMRAN"],
    ["1311", "JEFFERSON NG MING CAI"],
    ["1312", "CHOO JUN MENG ADEN"],
    ["1313", "LIEW BO XUAN, SVENSON"],
    ["1314", "LUKE PREVIN CLOVIS PAUL"],
    ["1315", "TAN E-SHEEN, BEVIS"],
    ["1402", "DIRK CYMON FERNANDEZ SANTOS"],
    ["1404", "WONG YU QUAN"],
    ["1405", "NATHAN YEO ZONG HAO"],
    ["1406", "YIN CHAO"],
    ["1407", "NG YONG PYNN"],
    ["1408", "HANS DANISH AMANI BIN ABAS"],
    ["1409", "GOH SHAN LUN"],
    ["1410", "LEE JIAN SHENG"],
    ["1411", "ASHVIN S/O A GUNASEGARAN"],
    ["1412", "LIN JUN QUAN"],
    ["1413", "HANSEL TAN CHENG XUAN"],
    ["1414", "ARAVINTH KUMAR"],
    ["1415", "LOKE ETHAN"],
    ["2101", "JOSHUA SOH"],
    ["2102", "MAXIMILIAN JONATHAN GEORGE"],
    ["2103", "RON TOH JIALE"],
    ["2104", "WONG YUAN AN AARON"],
    ["2105", "CHEN YIHENG"],
    ["2107", "MUHAMMAD IZZ BIN MARIIH"],
    ["2108", "CHUA KWEE KENG FERNANDEZ"],
    ["2109", "GAIUS TAN WAYNE HENG"],
    ["2110", "KEVIN LEE WEN WEI"],
    ["2111", "GULSHAN ALI BIN BASITH ALI"],
    ["2112", "SETH LIM RONG ZHE"],
    ["2113", "AHMAD SHAH REDHA BIN RHYME"],
    ["2114", "KONG DESHUO"],
    ["2115", "AZARRAGA ALEX ANGELO SENEN"],
    ["2116", "LIM CHER RAE MAXIMUS"],
    ["2201", "CHUA JUN YANG, RYAN"],
    ["2202", "NOORAFANDI SHAH BIN AZLAM SHAH"],
    ["2203", "KOON CHIN SUAN, JARREL"],
    ["2204", "NAWASSUL NAWI BIN MOHAMED ZIN"],
    ["2205", "YAP SHENG ZHE SHAUN"],
    ["2206", "WILSON YONG ZONG XUAN"],
    ["2207", "YIN QIN EN MATTHEW"],
    ["2208", "BAUTISTA CHRISTIAN JAY MESANA"],
    ["2209", "LIM ZUN HUI"],
    ["2210", "IBRAHIM MUHAMMAD BIN MOHD AZAR"],
    ["2211", "SHYAM MENON"],
    ["2212", "LEE WEN JIE"],
    ["2213", "KUNALAN BATHMANATHAN"],
    ["2214", "LAW KHEE NGEE ROYSTON"],
    ["2215", "TAN GUAN YUE"],
    ["2216", "TAI SHAO YANG"],
    ["2302", "GOH ZHI YANG"],
    ["2304", "BRANDON TAN HUP LE"],
    ["2305", "DON WONG TIAN CI"],
    ["2306", "CRAIG NG"],
    ["2307", "LIM HO YONG, JOEL"],
    ["2308", "MUHAMMAD FARIDUDDIN BIN SUHAIMI"],
    ["2309", "JAPHETH SONG JING HUI"],
    ["2310", "LEE YONG LIANG"],
    ["2311", "ETHAN TAN XIANG ZHI"],
    ["2312", "TAY ZI WEN"],
    ["2313", "WONG YUAN ZHI, IAN"],
    ["2314", "ARUL KUMARAN TAMIZH INIYAN"],
    ["2401", "XAVIER SEAH ZHENG WEI"],
    ["2402", "MOHAMMED AZHIM BIN MOHAMMED FAHMI"],
    ["2403", "WAN PENG KIT"],
    ["2404", "LEE MENG KIAT JORDAN"],
    ["2405", "LAU WEI JIAN"],
    ["2406", "CHARN KIT YU, LUKE"],
    ["2407", "GAVRYLL SINGH S/O MAVIN SINGH"],
    ["2408", "KIANG YE HONG"],
    ["2409", "LEE YU HUI DARREN"],
    ["2410", "ANG WEI XIANG"],
    ["2411", "GORDON LAW"],
    ["2412", "RAMASAMY VENKIDUPATHI"],
    ["2413", "CHUA ZHENGHAO"],
    ["2414", "ANG CHUAN JIE"],
    ["2415", "TAN YI JIE"],
  ];

  // Define the companyId you want to link these recruits to
  const companyId = 1; // Replace with your actual company ID

  for (const [id, name] of recruits) {
    const platoon = parseInt(id[0]);
    const section = parseInt(id[1]);
    const bed = parseInt(id.slice(2));

    await prisma.recruit.create({
      data: {
        id,
        name,
        platoon,
        section,
        bed,
        companyId,
      },
    });
  }

  console.log("Recruits added successfully!");
}
